---
- name: Expose port 8080 to internal network
  hosts: Beldam
  vars:
    http_port: 8080/tcp
    komga_port: 25600/tcp
  tasks:
    - name: Allow HTTP traffic
      ansible.posix.firewalld:
        port: "{{ http_port }}"
        zone: public
        state: enabled
        immediate: true
        permanent: true
    - name: Allow HTTP traffic for Komga
      ansible.posix.firewalld:
        port: "{{ komga_port }}"
        zone: public
        state: enabled
        immediate: true
        permanent: true