---
- name: Expose port 8080 to internal network
  hosts: Beldam
  vars:
    http_port: 8080
    internal_network: "192.168.1.0/24"
  tasks:
    - name: Allow traffic from internal network
      ansible.posix.firewalld:
        source: "{{ internal_network }}"
        zone: public
        state: enabled
        immediate: true
        permanent: true
    - name: Allow HTTP traffic
      ansible.posix.firewalld:
        port: 8080/tcp
        zone: public
        state: enabled
        immediate: true
        permanent: true