---
- name: Playbook to gather facts.....and do sshd i guess
  gather_facts: true
  hosts: Komga
  vars:
    sshd:
      MaxAuthTries: 10
  roles:
    - role: redhat.rhel_system_roles.sshd

  tasks:
    - name: Play 1 pong it
      ansible.builtin.ping:

    - name: Play 2 for sshd

